// const os = require("os");
// const {totalmem,freemem} = require("os");
// console.log(totalmem());
// console.log(freemem());
// console.log(__dirname);
// console.log(__filename);
const path = require("path");
const extensionName = path.extname("index.html");
console.log(extensionName);
const joinName = path.join(__dirname+"/Lesson2");
console.log(joinName);
